name: 'Bluestep Azure Firewall Rules'
trigger: none

variables:
  solution: 'bluestep-firewall-rules'
  artifactName: 'azure-firewall-rules-artifact'
  Production: 'Bluestep Production Connectivity Subscription'
  environmentProd: 'Bluestep-Production'
  Subscriptionid: '2887160a-ea77-4845-aba8-644475701efa'
  resourceGroupName: 'rg-hub-prod-we'

pool:
  vmImage: "windows-latest"

stages:
- stage: Build
  jobs:
  - job: UploadArtifact
    steps: 
    - checkout: self
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)\$(solution)'
        Contents: '**'
        TargetFolder: '$(Pipeline.Workspace)\$(solution)'
    - task: AzurePowerShell@5
      displayName: 'Creating rule files'
      inputs:
        azureSubscription: '$(Production)'
        ScriptType: 'FilePath'
        ScriptPath: '$(Pipeline.Workspace)\$(solution)\scripts\create-rule-files.ps1'
        azurePowerShellVersion: 'LatestVersion'
        workingDirectory: '$(Pipeline.Workspace)\$(solution)'
        pwsh: true
    - task: AzurePowerShell@5
      displayName: 'Build the artifact using PowerShell'
      inputs:
        azureSubscription: '$(Production)'
        ScriptType: 'FilePath'
        ScriptPath: '$(Pipeline.Workspace)\$(solution)\scripts\Build.ps1'
        azurePowerShellVersion: 'LatestVersion'
        workingDirectory: '$(Pipeline.Workspace)\$(solution)'
        pwsh: true
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Pipeline.Workspace)\$(solution)'
        flattenFolders: false
        Contents: |
          main.bicep
          main.json
          deploy.ps1
          bicepconfig.json
          modules/resourceLock.bicep
          modules/resourceLock.json
          scripts/CustomWhatif.ps1
          scripts/UnlockRG.ps1
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: '$(artifactName)'
        publishLocation: 'Container'
- stage: ValidateARM
  dependsOn: Build
  jobs:
  - job: ValidateDeployment
    steps:
    - checkout: none
    - task: DownloadBuildArtifacts@0
      inputs:
        downloadPath: '$(Pipeline.Workspace)'
        downloadType: 'single'
        artifactName: '$(artifactName)'
    - task: AzurePowerShell@5
      displayName: 'ARM-TTK validation'
      inputs:
        azureSubscription: '$(Production)'
        ScriptType: 'inlineScript'
        Inline: |
          Write-Verbose "Downloading the latest version of ARM-TTK from github, please wait.." -Verbose
          Git clone https://github.com/Azure/arm-ttk.git "$env:TMP\git"
          Import-Module "$env:TMP\git\arm-ttk\arm-ttk.psm1" -ErrorAction Stop
          Test-AzTemplate -TemplatePath "$(Pipeline.Workspace)\$(artifactName)\main.json" -skip @('DeploymentTemplate-Must-Not-Contain-Hardcoded-Uri','Location-Should-Not-Be-Hardcoded','Parameters-Must-Be-Referenced','Variables-Must-Be-Referenced','Template-Should-Not-Contain-Blanks','apiversions-should-be-recent')
        azurePowerShellVersion: 'LatestVersion'
        scriptPath: '$(Pipeline.Workspace)\$(artifactName)'
        pwsh: true
    - task: AzurePowerShell@5
      displayName: 'Unlock resource group'
      inputs:
        azureSubscription: '$(Production)'
        ScriptType: 'FilePath'
        ScriptPath: '$(Pipeline.Workspace)\$(artifactName)\scripts\UnlockRG.ps1'
        ScriptArguments: -SubscriptionId $(Subscriptionid) -RGName $(resourceGroupName)
        azurePowerShellVersion: 'LatestVersion'
        workingDirectory: '$(Pipeline.Workspace)\$(artifactName)'
        pwsh: true
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: '$(Production)'
        subscriptionId: '$(Subscriptionid)'
        resourceGroupName: '$(resourceGroupName)'
        location: 'West Europe'
        templateLocation: 'Linked artifact'
        csmFile: '$(Pipeline.Workspace)\$(artifactName)\main.json'
        deploymentMode: 'Validation'
- stage: WhatifDeploy
  dependsOn: ValidateARM
  jobs:
  - job: WhatIfDeployment
    steps:
    - checkout: none
    - task: DownloadBuildArtifacts@0
      inputs:
        downloadPath: '$(Pipeline.Workspace)'
        downloadType: 'single'
        artifactName: '$(artifactName)'
    - task: AzurePowerShell@5
      displayName: 'Bluestep Azure Firewall Rules Whatif'
      inputs:
        azureSubscription: '$(Production)'
        ScriptType: 'FilePath'
        ScriptPath: '$(Pipeline.Workspace)\$(artifactName)\deploy.ps1'
        ScriptArguments: -Whatif -ResourceGroupName '$(resourceGroupName)'
        azurePowerShellVersion: 'LatestVersion'
        workingDirectory: '$(Pipeline.Workspace)\$(artifactName)'
        pwsh: true
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: '$(Production)'
        subscriptionId: '$(Subscriptionid)'
        resourceGroupName: '$(resourceGroupName)'
        location: 'West Europe'
        templateLocation: 'Linked artifact'
        csmFile: '$(Pipeline.Workspace)\$(artifactName)\modules\resourceLock.json'
        deploymentMode: 'Incremental'
    - task: AzurePowerShell@5
      displayName: 'Bluestep Custom Whatif'
      inputs:
        azureSubscription: '$(Production)'
        ScriptType: 'FilePath'
        ScriptPath: '$(Pipeline.Workspace)\$(artifactName)\scripts\CustomWhatif.ps1'
        azurePowerShellVersion: 'LatestVersion'
        workingDirectory: '$(Pipeline.Workspace)\$(artifactName)'
        pwsh: true
- stage: Deploy_Azure_Firewall_Rules
  dependsOn: WhatifDeploy
  jobs:
  - deployment: DeployFirewallRules
    timeoutInMinutes: 360
    displayName: Deploy Azure Firewall Rules for production
    environment: '$(environmentProd)'
    strategy:
     runOnce:
      deploy:
        steps:
        - task: AzurePowerShell@5
          displayName: 'Unlock resource group'
          inputs:
            azureSubscription: '$(Production)'
            ScriptType: 'FilePath'
            ScriptPath: '$(Pipeline.Workspace)\$(artifactName)\scripts\UnlockRG.ps1'
            ScriptArguments: -SubscriptionId $(Subscriptionid) -RGName $(resourceGroupName)
            azurePowerShellVersion: 'LatestVersion'
            workingDirectory: '$(Pipeline.Workspace)\$(artifactName)'
            pwsh: true
        - task: AzurePowerShell@5
          displayName: 'Bluestep Azure Firewall Rules deploy'
          inputs:
            azureSubscription: '$(Production)'
            ScriptType: 'FilePath'
            ScriptPath: '$(Pipeline.Workspace)\$(artifactName)\deploy.ps1'
            ScriptArguments: -ResourceGroupName '$(resourceGroupName)'
            azurePowerShellVersion: 'LatestVersion'
            workingDirectory: '$(Pipeline.Workspace)\$(artifactName)'
            pwsh: true
